compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]
name = "cfw-geoip"
main = "src/index.js"

# R2 bucket bindings
[[r2_buckets]]
binding = "GEO_BUCKET"
bucket_name = "geo-mmd"

# Environment variables
[vars]
MMDB_PATH = "GeoLite2-City/latest/GeoLite2-City.mmdb"
CACHE_TTL = "86400"  # 24小时缓存
